services:
  web:
    build: .
    ports:
      - "8000:8000"
    
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    depends_on:
      - db
    networks:
      - messages

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    
    networks:
      - messages

  bot:
    image: notes_tg
    container_name: 'notes_tg'
    ports:
      - "8001:8001"

    environment:  
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    depends_on:
     - db
     - web
    
    networks:
      - messages


networks:
  messages:
    driver: bridge

