"""add CASCADE

Revision ID: ad22d8589ed1
Revises: 128f8b2ac020
Create Date: 2024-09-16 13:32:40.682474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad22d8589ed1'
down_revision: Union[str, None] = '128f8b2ac020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('record_auther_fkey', 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'user', ['auther'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tagsrecord_record_id_fkey', 'tagsrecord', type_='foreignkey')
    op.drop_constraint('tagsrecord_tag_id_fkey', 'tagsrecord', type_='foreignkey')
    op.create_foreign_key(None, 'tagsrecord', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tagsrecord', 'record', ['record_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('usertg_user_id_fkey', 'usertg', type_='foreignkey')
    op.create_foreign_key(None, 'usertg', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usertg', type_='foreignkey')
    op.create_foreign_key('usertg_user_id_fkey', 'usertg', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'tagsrecord', type_='foreignkey')
    op.drop_constraint(None, 'tagsrecord', type_='foreignkey')
    op.create_foreign_key('tagsrecord_tag_id_fkey', 'tagsrecord', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('tagsrecord_record_id_fkey', 'tagsrecord', 'record', ['record_id'], ['id'])
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key('record_auther_fkey', 'record', 'user', ['auther'], ['id'])
    # ### end Alembic commands ###
